-- ============================================================================
-- Hamsun Supply — grouped, numbered requests (Slack + web), with the
-- accept → collect state machine.
--
--   req_orders        one request slip: #number, who asked, which dept, status
--   req_order_items   the lines on that slip (item + quantity), snapshotted
--
-- Stock is only subtracted when the person clicks "Collect" (one 'out'
-- movement per line) — never at accept time. History stays append-only.
-- ============================================================================

create table if not exists invtt.req_orders (
  id                 uuid primary key default gen_random_uuid(),
  number             bigint generated by default as identity,
  property_id        uuid references invtt.properties(id) on delete cascade,
  department_id      uuid references invtt.departments(id) on delete set null,
  department_name    text,                 -- snapshot for display / PDF
  requester_name     text,
  requester_slack_id text,
  source             text not null default 'slack' check (source in ('slack','web','portal')),
  status             text not null default 'pending'
                       check (status in ('pending','accepted','rejected','collected')),
  reject_reason      text,
  slack_channel      text,                 -- where to post the Collect button
  slack_thread_ts    text,                 -- thread to reply in
  decided_by         uuid references invtt.profiles(id),
  seen_at            timestamptz,
  created_at         timestamptz not null default now(),
  decided_at         timestamptz,
  collected_at       timestamptz
);
create unique index if not exists req_orders_number_idx on invtt.req_orders(number);
create index if not exists req_orders_status_idx on invtt.req_orders(status, created_at desc);

create table if not exists invtt.req_order_items (
  id        uuid primary key default gen_random_uuid(),
  order_id  uuid not null references invtt.req_orders(id) on delete cascade,
  item_id   uuid references invtt.items(id) on delete set null,
  item_name text not null,                 -- snapshot
  unit      text,                          -- snapshot (the unit Areeba set)
  quantity  numeric not null check (quantity > 0)
);
create index if not exists req_order_items_order_idx on invtt.req_order_items(order_id);

-- RLS: keeper-only read; service_role (Edge Functions) does all writes --------
alter table invtt.req_orders      enable row level security;
alter table invtt.req_order_items enable row level security;
drop policy if exists read_keeper on invtt.req_orders;
create policy read_keeper on invtt.req_orders      for select to authenticated using (invtt.is_keeper());
drop policy if exists read_keeper on invtt.req_order_items;
create policy read_keeper on invtt.req_order_items for select to authenticated using (invtt.is_keeper());
grant select on invtt.req_orders      to authenticated;
grant select on invtt.req_order_items to authenticated;
grant all on all tables in schema invtt to service_role;

-- live notifications for Areeba when a Slack request lands -------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'invtt' and tablename = 'req_orders'
  ) then
    alter publication supabase_realtime add table invtt.req_orders;
  end if;
end $$;

notify pgrst, 'reload schema';
